// const emergencies = [
//   {
//     _id: 1,
//     data: {
//       patient_id: 1,
//       emergencyDetails: 'Person(s) are injured',
//       emergencyType: 'ambulance',
//       affectedPersons: 'Caller & another Person',
//       emergencyNote: "Left leg is broken - can't move",
//       city: 'Bozen',
//       country: 'Italy',
//       location: { latitude: 46.496719, longitude: 11.358 },
//     },
//   },
//   {
//     _id: 2,
//     data: {
//       patient_id: 2,
//       emergencyDetails: 'Person(s) are injured',
//       emergencyType: 'ambulance',
//       affectedPersons: 'Caller & another Person',
//       emergencyNote: "Can't feel my right hand",
//       city: 'Munich',
//       country: 'Germany',
//       location: { latitude: 48.135124, longitude: 11.581981 },
//     },
//   },
//   {
//     _id: 3,
//     data: {
//       patient_id: 3,
//       emergencyDetails: 'Person(s) are injured, Life is at danger',
//       emergencyType: 'ambulance',
//       affectedPersons: 'Caller',
//       emergencyNote: 'Got bitten by a snake',
//       city: 'Bozen',
//       country: 'Italy',
//       location: { latitude: 46.496719, longitude: 11.358 },
//     },
//   },
//   {
//     _id: 4,
//     data: {
//       patient_id: 4,
//       emergencyDetails: 'Person(s) are injured, Life is at danger',
//       emergencyType: 'ambulance',
//       affectedPersons: 'another Person',
//       emergencyNote: "Left leg is broken - can't move",
//       city: 'Bozen',
//       country: 'Italy',
//       location: { latitude: 46.496719, longitude: 11.358 },
//     },
//   },
//   {
//     _id: 5,
//     data: {
//       patient_id: 5,
//       emergencyDetails: 'Person(s) are injured, Life is at danger',
//       emergencyType: 'police',
//       affectedPersons: 'another Person',
//       emergencyNote: "Left leg is broken - can't move",
//       city: 'Bozen',
//       country: 'Italy',
//       location: { latitude: 46.496719, longitude: 11.358 },
//     },
//   },
// ];

const emergencies = [
  {
    _id: 1,
    data: {
      patient_id: 1,
      emergencyDetails: 'Injury',
      emergencyType: 'ambulance',
      affectedPersons: 'Caller',
      emergencyNote: "Left leg is broken - can't move",
      city: 'Zugspitze',
      country: 'Germany',
      location: { latitude: 47.423371, longitude: 10.99961 },
      emergencyStatus: 0,
    },
  },
  {
    _id: 2,
    data: {
      patient_id: 2,
      emergencyDetails: 'Poisoned',
      emergencyType: 'ambulance',
      affectedPersons: 'Caller & another Person',
      emergencyNote: "Can't feel my right hand",
      city: 'Wettersteinspitze',
      country: 'Germany',
      location: { latitude: 47.429198, longitude: 11.220673 },
      emergencyStatus: 1,
    },
  },
  // {
  //   _id: 3,
  //   data: {
  //     patient_id: 3,
  //     emergencyDetails: 'Person(s) are injured, Life is at danger',
  //     emergencyType: 'ambulance',
  //     affectedPersons: 'Caller',
  //     emergencyNote: 'Got bitten by a snake',
  //     city: 'Bozen',
  //     country: 'Germany',
  //     location: { latitude: 46.496719, longitude: 11.358 },
  //   },
  // },
  {
    _id: 4,
    data: {
      patient_id: 4,
      emergencyDetails: 'Life is at danger',
      emergencyType: 'ambulance',
      affectedPersons: 'another Person',
      emergencyNote: 'My dad had a stroke',
      city: 'Ettaler Forst',
      country: 'Germany',
      location: { latitude: 47.52851, longitude: 10.927604 },
      emergencyStatus: 1,
    },
  },
  {
    _id: 5,
    data: {
      patient_id: 5,
      emergencyDetails: 'Theft',
      emergencyType: 'police',
      affectedPersons: 'another Person',
      emergencyNote: 'My backpack was stolen.',
      city: 'Walchensee',
      country: 'Germany',
      location: { latitude: 47.572447, longitude: 11.337582 },
      emergencyStatus: 1,
    },
  },
];

const users = [
  {
    _id: 1,
    data: {
      fullname: 'Sophie Lange',
      birthday: '11.7.1993',
      allergies: 'Penicillin',
      medical_conditions: 'Asthma',
      address: 'Neureutherstraße 5',
      nationality: 'german',
      blood_group: 'B+',
      fullname_relative_1: 'Michael Ballack',
      fullname_relative_2: 'Heidi Klum',
      phone_number_relative_1: '0800 999 999',
      phone_number_relative_2: '0800 999 999',
    },
  },
  {
    _id: 2,
    data: {
      fullname: 'Alexander Farr',
      birthday: '11.11.1990',
      allergies: '',
      medical_conditions: 'Diabetes',
      address: 'Zwillingstrasse 4',
      nationality: 'german',
      blood_group: 'A+',
      fullname_relative_1: 'Michael Ballack',
      fullname_relative_2: 'Heidi Klum',
      phone_number_relative_1: '0800 999 999',
      phone_number_relative_2: '0800 999 999',
    },
  },
  {
    _id: 3,
    data: {
      fullname: 'Max Mynter',
      birthday: '3.7.1996',
      allergies: 'nuts',
      medical_conditions: 'broken leg (2015)',
      address: 'Theresienstrasse 9',
      nationality: 'german',
      blood_group: 'A+',
      fullname_relative_1: 'Michael Ballack',
      fullname_relative_2: 'Heidi Klum',
      phone_number_relative_1: '0800 999 999',
      phone_number_relative_2: '0800 999 999',
    },
  },
  {
    _id: 4,
    data: {
      fullname: 'Ali Khan',
      birthday: '11.03.1994',
      allergies: '',
      medical_conditions: 'broken nose',
      address: 'Berliner Strasse 28',
      nationality: 'german',
      blood_group: 'A+',
      fullname_relative_1: 'Michael Ballack',
      fullname_relative_2: 'Heidi Klum',
      phone_number_relative_1: '0800 999 999',
      phone_number_relative_2: '0800 999 999',
    },
  },
  {
    _id: 5,
    data: {
      fullname: 'Amadea Pely',
      birthday: '10.01.1995',
      allergies: 'pollen',
      medical_conditions: '',
      address: 'Marsstraße 20',
      nationality: 'german',
      blood_group: 'A+',
      fullname_relative_1: 'Michael Ballack',
      fullname_relative_2: 'Heidi Klum',
      phone_number_relative_1: '0800 999 999',
      phone_number_relative_2: '0800 999 999',
    },
  },
];

export { users, emergencies };
